### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by benbuffone** [crotis/Kittens#1]
ERROR in ./src/js/pages/Paste.js
Module not found: Error: Cannot resolve module 'react-fetch' in /Users/benbuffone/Projects/Kittens-master/src/js/pages
 @ ./src/js/pages/Paste.js 14:18-40

ERROR in ./src/js/pages/Kittens.js
Module not found: Error: Cannot resolve module 'react-fetch' in /Users/benbuffone/Projects/Kittens-master/src/js/pages
 @ ./src/js/pages/Kittens.js 16:18-40

ERROR in ./src/js/pages/Paste.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../containers/kitten-list in /Users/benbuffone/Projects/Kittens-master/src/js/pages
 @ ./src/js/pages/Paste.js 18:18-54

ERROR in ./src/js/pages/Layout.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../reducers in /Users/benbuffone/Projects/Kittens-master/src/js/pages
 @ ./src/js/pages/Layout.js 34:16-38

ERROR in ./src/js/dispatcher.js
Module not found: Error: Cannot resolve module 'flux' in /Users/benbuffone/Projects/Kittens-master/src/js
 @ ./src/js/dispatcher.js 7:12-27
webpack: Failed to compile.

**Comment by benbuffone** [comment]
> Kittens@0.0.0 dev /Users/benbuffone/Projects/Kittens-master
> webpack-dev-server --content-base src --inline --hot

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! Kittens@0.0.0 dev: `webpack-dev-server --content-base src --inline --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Kittens@0.0.0 dev script 'webpack-dev-server --content-base src --inline --hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Kittens package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base src --inline --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Kittens
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Kittens
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benbuffone/Projects/Kittens-master/node_modules/npm-debug.log
